Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
